version: '3.4'

services:
  secretkeeper:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 44340
        published: 44340
        protocol: tcp
        mode: host

networks:
  default:
    external:
      name: nat  