version: '3.4'

services:
  secretkeeper:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host

networks:
  default:
    external:
      name: nat  